version: '3'

services:
  postgres:
    image: postgres:16.0
    env_file:
      - ./compose.env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  web:
    build: ./image_upload
    env_file:
      - ./compose.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
